### PR TITLE
Simple sentences

### PR DESCRIPTION
**Pull request by aaronbrowder**
This creates a new "simple view" for the sentences list. See comments for screenshots.

### CODE REVIEW

**Comment by aaronbrowder** [comment]
image

image

**Comment by schmave** [comment]
Hi Aaron, thanks for the contribution! Sorry for my long delay in replying. I like the idea of being able to format this list in a different way, but I have some reservations about it.

"simple" and "detailed" aren't great words to describe the different views. I mean, one is certainly simpler, but it's not the only possible simple view. Why do recently completed sentences disappear in the simple view? I guess that's part of it being simpler. 

I think the bigger issue is that for most schools, neither of these two views are probably exactly the format that the school would like. This PR complicates the interface without satisfying the school's desire for what they want. 

Would you be up for making this more customizable? There could be a settings screen that lets you pick whether you want a table or a list, and then which fields you want to have displayed in your table or list. No matter what you choose, active and recently completed sentences could be shown, as well as the checkbox to modify the completion boolean. 

That version would certainly add complexity too. And it probably would meet your needs less, because presumably you want both the detailed view and the simple view at different times. But maybe not? 

What do you think?

**Comment by aaronbrowder** [comment]
I do need both views at different times. We will use the simple view most of the time because people just need to know "what do I have to do today?" and the simple view is more readable if that's all you need. But occasionally someone will ask, "why do I have that sentence?" and then we need to be able to see the charges and findings too.

I originally envisioned this change as just having a second print button beside the existing print button that would print sentences in a different format. But that would not be possible because the print button just prints the current page's HTML, so I had to create a separate page. I excluded the checkboxes and the recently completed sentences in the simple view because those things don't get printed.

The problem is that we don't know what format(s) each school would really like to have. We could make both views customizable in the settings, and I think that would be an improvement. Though, what customizations would be available? The only things I can think of are (A) whether to show the findings in the table view, and (B) whether to show the charges in the list view. To me it doesn't make sense to show findings in the list view because each list item is just unformatted text, and the sentence would get buried by the findings. Maybe there are other customizations that other schools would like, but we can't know what those are unless we actually know what formats those schools prefer.

**Comment by schmave** [comment]
Thanks for the additional info! I'll try a somewhat configurable solution this weekend.

**Comment by aaronbrowder** [comment]
I messed around with making this customizable, but ran into issues. Being able to check/uncheck sentences (which moves them to another section) is difficult in the simple view because in that view sentences are grouped by person. It makes sense for the simple view to be read-only for that reason.

Instead, I've changed it so that the simple view automatically goes to print. So now, on the sentences page there are two print buttons at the top: "print active sentences" and "print simple view" which are just different print formats. This is more what I had in mind when I originally envisioned this feature.

**Comment by schmave** [comment]
Cool, looks good to me. Thanks for taking a second pass at this.

**Comment by schmave** [comment]
I've deployed this PR and your other as well. Let me know if you see anything strange.

**Comment by aaronbrowder** [comment]
Thanks!

**Pull request merged**
