### PR TITLE
Checkin app

### PR DESCRIPTION
**Pull request by aaronbrowder**
This is all finished except for the authentication part. I was wondering if you would be up for working on that, or pointing me in the right direction if you don't have time to work on it. I haven't figured out how to enable or test authentication in my dev environment. My thought is that the checkin actions should not require authentication, as long as the device or IP address is authenticated. I don't want to ever have to sign in to use this app. My understanding is that this is similar to how Custodia works.

First you will need to assign PINs to people by going to Attendance > Assign PINs. Then you can access the app at Attendance > Check-in app. Once you are there, you should be able to install the web app on your tablet or phone as if it were a native app. (On my phone this feature is called "Add to home screen".) After the initial page load, you can use the app indefinitely without internet connection. The app will sync all data with the server as soon as a connection becomes available.

The app never overwrites data on the server, so if there is already attendance data for that person on that date, the app will not change it. This ensures that data entered by an admin is considered authoritative.

The app is a progressive web app (PWA) and is completely self-contained under /assets/checkin. This seems like a weird architecture, but it was simpler to build self-contained this way. The PWA is governed by a service worker -- a browser process which makes a web app behave like a native app -- which by default serves all files in and under the directory where it lives (which means it will not work if the URL is /attendance/checkin, it has to be /assets/checkin). These files are cached in the browser so you don't need an internet connection to load the app. App data is stored in IndexedDB in the browser via localforage.

We will need to test this on a variety of devices. Maybe if we can roll it out before the summer's over, we can do some live testing.

Let me know if you have any questions, concerns, or suggestions.

### CODE REVIEW

**Comment by aaronbrowder** [comment]
By the way, I just realized the app won't work on Saturday or Sunday.

**Comment by schmave** [comment]
Hi Aaron. I'm really sorry about my slow response to this PR. Now that I've taken my first look I think I can be much faster about future ones. When does school start for you guys?

Using a service worker is really cool -- it really works even when offline!

Here are the things that I think should be added so that this is widely useful. Let me know what you think:

* There should be some indication that your signins/out are not yet saved because the server is unreachable.
* Shouldn't hide the pin with asterisks. It makes it too hard for people to know if they made a typo or not.
* Should have a way for a student to see if they are signed in already.
* Should have a way for an administrator (or everyone) to see the entire list of who is here and who is not. (This could be in the DemSchoolTools Attendance tab, or in the signin app)
* Should have confirmation screen so that if you type in the wrong PIN, it's obvious and you can cancel.
* The savepins route should use POST method instead of GET
* Should show notification of some kind if signin/out wasn't saved because there was already existing data. Ideally, it would probably say what the existing data is.


Yes, the authentication is an issue too. I think that this signin app needs to require a password. The way I did it for Custodia is that I fixed a username per-school and let people set a password on the settings page. That username and password can be used to sign in to Custodia in a non-administrator way, suitable for students to sign in and out but not modify historical data. I can help do this if you'd like. The user/password logic is all handled in Custodia, so it's not particularly easy to migrate into DST. Since DST now supports user/password logins, I think it shouldn't be much work for me to add this.

**Comment by aaronbrowder** [comment]
Our school year starts on September 3.

It would be great if you can tackle the authentication stuff. I can't make heads or tails of DST authentication.

Here are my thoughts regarding your confirmation screen idea, and the asterisks. For one, the PIN is intended to be secret, and long enough that it's virtually impossible to enter a PIN that you don't know. So the confirmation screen seems like an unnecessary step, and even problematic in the case of non-literate students, especially little kids. As far as typos go, they should not be a problem because if you make a typo you will get the error screen and have to try again; there will be no incorrect data saved. Thoughts?

I can make it so if you sign in or out and the data is not saved because there is already data for that slot, it shows a yellow warning sign instead of the green check mark, and also tell you what data the server has for that slot. If a student wants to know whether they are already signed in, they can just try to sign in and see if they get this warning sign. I can also add a "roster" button to the app which shows the full list of students with the times they arrived and departed today.

I considered creating a notification bar at the bottom of the screen which would pop up if the app is offline and say something like "Offline. Data will sync with the server when connection becomes available." I decided not to do that because that much text would need two lines and there is not much space available on screen. I also considered making the message just "Offline" but I fear users would interpret that to mean the app is unusable, when in fact the app works just fine indefinitely while offline and this is no cause for concern. So I want to avoid taking up screen space and alarming users about a fact that in all likelihood doesn't matter. The only time offline matters is when you try to retrieve the roster, and it will fail to retrieve if offine, so at that point you can identify the problem and troubleshoot.

**Comment by aaronbrowder** [comment]
Evan, I plan to make the changes I described in my previous comment this week (the last week before school starts). When do you think you'll get around to the authentication stuff?

**Comment by schmave** [comment]
Thanks for your replies about my design suggestions. The idea of using long PINs makes a big difference! Given that we've probably missed the boat for getting people off of Custodia and on to this this year, your school will have some time as the sole user of the new system and will be able to experiment and find out what works best, so I'm going to defer to you about design stuff for now. 

I can get the authentication part done within a week.

Will you push to this branch when you are ready?

**Comment by aaronbrowder** [comment]
Yes I'll do that, thank you. It will be good to have The Open School use it for a while to work out the issues before others adopt it.

**Comment by aaronbrowder** [comment]
I'm done with the changes I was going to make.

**Comment by aaronbrowder** [comment]
There was a feature which I said I was going to add but I realized it doesn't make sense:

> I can make it so if you sign in or out and the data is not saved because there is already data for that slot, it shows a yellow warning sign instead of the green check mark, and also tell you what data the server has for that slot. If a student wants to know whether they are already signed in, they can just try to sign in and see if they get this warning sign.

The problem is that in offline mode, the app won't know whether there is existing data or not. I could show the warning sign in the event that we are online, but there will still be cases where we are offline and it can't be determined whether the sign in was successful or not, and we have to assume that it was successful because it will be most of the time. But users cannot assume that they are successfully signed in just because the app tells them so, if that makes sense.

A user can still check what data the server has at any time by tapping the "Roster" button. The roster always shows live server data, so if the app is offline it will say so.

**Comment by schmave** [comment]
Nice!

I just added the authentication backend, plus settings for controlling the visibility of the checkin app and the password. The username and password are hard-coded right now in app.js. If you can add the GUI for signing in, then I think we're good to go. 

I don't know how deployment works with a service worker. What do we need to do to make sure that when we push a new version to the server, the browser loads the latest version?

**Comment by aaronbrowder** [comment]
At the top of service-worker.js there is a CACHE_NAME that should be incremented every time the front-end code changes.

**Comment by aaronbrowder** [comment]
I added the GUI for signing in. I also changed the javascript architecture a bit so that it detects when you are no longer logged in and automatically tries to log you in.

This code doesn't work, because I couldn't figure out how to detect whether a login is successful or not. The problematic code is in app.js on line 65. It seems that the response from a POST to /login always has the status code 0 and has no information that would allow us to identify whether it was successful. On the other hand, when I log in to demschooltools normally, the response code for POST to /login is always 303. Maybe you can make some sense of it?

**Comment by schmave** [comment]
I fixed the authentication stuff and deployed it to the live site. Take a look and let me know how it looks!

**Comment by aaronbrowder** [comment]
Thanks! Looks like it's working. I'm noticing some styling issues when viewing on different devices, so I'll create an update probably on Sunday.

**Pull request merged**
