### PR TITLE
Checkin app fix

### PR DESCRIPTION
**Pull request by aaronbrowder**
There are a couple of bugs I needed to fix in addition to the cosmetic changes. One of them is a time zone bug I don't quite understand. It works fine for me locally, but on the live site it's persisting times in UTC. It seems that java.sql.Time implicitly converts milliseconds since epoch to the server local time? I created a fix, but I can't know if it works or not until it's deployed.

### CODE REVIEW

**Comment by aaronbrowder** [comment]
Did you see this? When do you think you'll be able to merge it?

**Comment by schmave** [comment]
Sorry for the delay. I just deployed this now. I'm going to take a look at the time zone stuff and see if I have any recommendation...

**Comment by schmave** [comment]
Time zone bugs can be very tricky. Without more detail about what's going on, I can't easily provide much advice. You're right that the time values stored with AttendanceDay objects need to be in UTC time. The server's local time zone is UTC. 

In order to make testing locally easier, you should get your server process to run with UTC as its local time zone while your web browser still uses your actual local time. I think that you can do this by setting the JAVA_OPTS environment variable before running sbt. This syntax works on Mac/Linux, though I'm not 100% certain that this is causing the server to run in UTC time zone (you should verify): 

    JAVA_OPTS='-Duser.timezone=UTC' sbt run

I think that your new code as of this PR will find the correct AttendanceDay in `findCurrentDay` because the `day` argument to that function is in the user's local time zone. I think it will then set the start_time and end_time incorrectly, though. But maybe I am mistaken and it works! Hopefully you can find a way to test this reliably on your local machine. Unit tests may be another tool that could be useful.

Let me know how it goes and if you want me to take a look at anything more.

**Comment by schmave** [comment]
FYI I had to manually clear the browser cache in order to see the new version of the roster close icon on this page: https://sandbox.demschooltools.com/assets/checkin/app.html 

So there may still be some improvements to be made to the deployment so that old versions aren't kept for longer than they should be.

**Pull request merged**
