### PR TITLE
Attendance rate bug fix

### PR DESCRIPTION
**Pull request by aaronbrowder**
Fix bug where "no school" days were being counted as absences for the attendance percent calculation

### CODE REVIEW

**Comment by schmave** [comment]
Deployed!

**Comment by aaronbrowder** [comment]
It looks like the bug is still happening. Are you sure it's been deployed? If so, do you have any ideas for debugging it? Would it be possible/easy for me to get a copy of The Open School's live data to test with locally?

**Comment by schmave** [comment]
It's possible that I didn't deploy this yesterday. I just redeployed now and I'm certain that I included this commit. Can you take another look? If it's still not fixed, let me know and I can provide some debugging tips.

**Comment by aaronbrowder** [comment]
Yes, it works now. Thank you!

**Pull request merged**
