### PR TITLE
Add attendance rate to Check-in hello screen

### PR DESCRIPTION
**Pull request by aaronbrowder**
I wanted to show a person's current attendance rate when they check in using the Check-in app. To do this, I needed to standardize the time frame over which the attendance rate is calculated (i.e. only look at the last 60 school days). This project includes:
1. Creating a setting for the number of school days to look in the past
2. Creating shared methods for computing attendance rate that can be used by both the Check-in app and the main Attendance tool
3. Displaying the attendance rate in the Check-in app
4. Adding a button to the Attendance By Year page to easily view the standard time frame for all students

### CODE REVIEW

**Comment by schmave** [comment]
Thanks, Aaron! I'll review this this week.

**Comment by aaronbrowder** [comment]
Hi Evan, do you have an estimate of when this will be complete? Thanks!

**Comment by schmave** [comment]
Interesting feature. Looks reasonable to me!

**Comment by schmave** [comment]
This is live on the site now. I enabled it for the TOS site and it seems to work. Let me know if you see any issues.

**Pull request merged**
